src/tools/bit2core.c
My work for card #11.
You did mention on Discord it'd be worth looking into the bitstream header info to confirm the board revision details in there.
I haven't tried doing that yet, as I'm not familiar with it, but I could try have a stab at it in a future card.
Also, I've left bit2core's internal logic as-is in regards to the skipping of the first 120 bytes of the bitstream. Presently, m65connect's convertor keeps these 120 bytes in the .cor file, so there's a discrepancy there.
Happy to hear any thoughts from you on this, think I had another card made for that topic, so will investigate that further there.
=> Bit2core 8mb

.travis.yml, Makefile, README.md, src/tests/test_335.c, src/tests/vicii.c, src/tools/fpgajtag/boundary_scan.c, src/tools/fpgajtag/fpgajtag.c, src/tools/m65.c, src/tools/m65common.c, src/tools/mega65_ftp.c, src/utilities/remotesd.c
Work done on card #35 to address all compiler warnings in the mega65-tools repo.
Some compiler warnings relating to code within the mega65-libc submodule will be addressed in the https://github.com/MEGA65/mega65-libc/issues/6 sibling card.
=> 35 compiler warnings

.travis.yml, Makefile, README.md, gtest/mega65_ftp_test.cpp, src/tests/m65ftp_test.c, src/tools/m65common.c, src/tools/mega65_ftp.c, src/tools/pngprepare/md2h65.c, src/utilities/gmod2-tools.c
Work done for card #45 to get mega65_ftp to read in double-quoted string parameters that contain spaces.
=> #45: MEGA65_FTP: Handle double-quoted parameters with spaces

Makefile, gtest/bit2core_test.cpp, gtest/mega65_ftp_test.cpp, include/dirtymock.h, src/tools/bit2core.c, src/tools/mega65_ftp.c
PR for work done on #19 for BIT2CORE, to add 'm65target' field into the generated .cor file
=> #19: Added 'm65target' and 'model_id' fields into .cor file

README.md
Currently the documentation has this command for installing the dependencies:
`sudo apt-get install git build-essential libusb-dev install libpng-dev libusb-1.0-0-dev libreadline-dev libgif-dev`
Due to `install `being an argument, trying to run this (on Ubuntu 18.04) results in the error:
`E: Unable to locate package install`
This PR removes the `install` argument.
=> Remove erroneous install argument from apt-get documentation

src/tools/m65.c, src/tools/m65common.c
I synchronized the m65 <-> HYPPO protocol for virtual f011 read and write, by halting the CPU while operating.
In that I reconized and fixed that stop_cpu acutally didn't stop the CPU because it was sending the t1 command using safe write before marking the CPU stopped which caused the CPU actually to be stopped and restarted.
=> Fixed (hopefully) by synchronize the m65 <-> HYPPO protocol 

src/tools/m65.c
Unit tests can now set their reported name, as well as log messages to the host computer's console.
An updated libc is needed to use this from C (see https://github.com/MEGA65/mega65-libc/pull/10)
=> Add unit test logging and test name capability to m65

src/tests/runTests.sh, src/tools/m65.c
- adds timeout for unit test mode
- return value now either 0 for "all tests passed", or number of failed tests
- new option "-w" for writing/appending unit test log files
- adds a (fairly simple and preliminary) test runner script that scans the current directory for *.prg files and launches each of them in m65 unit test mode, writing the aggregate results to "tests.log"
=> Unit test enhancements

README.md
This is an edit to `README.md` to include `libncurses5-dev`, as suggested in [#66](https://github.com/MEGA65/mega65-tools/issues/66).  This is required to make `mega65_ftp` on a fresh Ubuntu 18.02 install.
=> Fix #66 - Add libncurses5-dev as a required package to README.md

Makefile, src/tools/m65.c, src/tools/m65common.c, src/tools/mega65_ftp.c, src/utilities/remotesd.c
Work done for card #60, to improve comms between tools like m65/mega65_ftp and xemu over tcp port 4510.
For best results, run these tools against my [220-uartmon-update](https://github.com/gurcei/xemu/tree/220-uartmon-update) branch of xemu.
I've left a bit of debug stuff here and there, mostly commented out, particularly in remotesd.c, as I suspect it won't be the last time I need to debug in this vicinity.
=> #60: tweaks for xemu (to improve comms over tcp)

Makefile, src/tools/fpgajtag/fpgajtag.c, src/tools/fpgajtag/util.c, src/tools/m65.c
Work done for card #69.
The capability to upload bitstreams via m65 in windows is now possible. It's probably best for anyone considering that path to read through my experiences (bad and eventually good) with the zadig tool and installing a winusb driver for "Diligent USB Device (Interface 0)" (and not for (Interface 1)), which I've summarised on card #69 too.
=> #69: M65: get '-b' bitstream uploading working in windows

src/tools/m65.c
Detects USB permissions in order to disable the automatic device scan with insufficient permissions... thus making it possible to run m65 without root privileges on Linux.
=> disable device scan with insufficient permissions

Makefile, gtest/bit2core_test.cpp, gtest/mega65_ftp_test.cpp, include/m65common.h, src/tools/diskman.c, src/tools/diskman.h, src/tools/filehost.c, src/tools/filehost.h, src/tools/m65.c, src/tools/m65common.c, src/tools/mega65_ftp.c
As my vfat efforts took a tangent in different directions, I thought I better do a pull-request for the work done so far, as I'm worried if I wait till the complete vfat implementation is in, it'll be even larger, and an enormous pain to review.
So, work done so far:
- bringing across my prior vfat logic (for viewing the names of lfn entries)
- enabled Paul's lfn shortname logic, which needs some more tlc before we can make full use of it
- NOTE: I'll finalise vfat stuff in the next PR
- `fh` - lists the files on the filehost (prefacing each item with a numeric index)
- `fhget <idx>` - retrieves the indexed file from the filehost (.prg files are automatically wrapped into a .d81)
- Run mega65_ftp with `-u username -p pwd` args to also access private files on the filehost
- `dput …
=> #9: MEGA65_FTP: vfat (part 1), extra comfort commands and for accessing filehost easily

src/tools/png2fci.py
This adds the png2fci.py tool.
png2fci is used to convert PNG files to FCI files (which can be directly read and displayed by the FCIO library).
A working demo of FCI files in action can be seen here: https://github.com/steph72/fcio
=> add png2fci tool

Makefile, src/tests/qop_test.c, src/tests/test_458.c, src/tests/test_459.c, src/tools/m65.c
This adds a complete Q-Opcode Unit Test, which tests all the Q-Opcodes for all cases and all addressing modes.
The new test concept revolves around a list of test **Suites** which are defined by a set of **Modes** and **Tests**. Via flags all combinations of those modes and tests are tested and their result is recorded. Only failed tests are displayed, plus a summary line per suite is displayed. On the Hypervisor unit test line, all test results are transmitted.
**Note:** the qop-test.prg will show 29 errors on a recent core, because all Q-accumulator implied opcodes are not implemented yet.
Additional changes in this request:
Changes the timestamping of m65 unit test mode to ISO Format with microseconds, for easier parsing by consuming applications (also: asctime is obsolete by POSIX). …
=> Q-Opcode Unit Test

src/tools/m65.c
If you currently call
`m65 -F -4 -r -u src/tests/test_468.prg`
as before, it will silently not start the program.
Correct call is now:
`m65 -F -4 -r -u 60 src/tests/test_468.prg`
This patch will check if the argument to -u is actually a number, and if not will fail with a error message, so you know what you did wrong.
Just took me 30 min to see my error in the call introduced by my own patch...
=> Better handling of new -u argument

Makefile, src/tests/test_468.c
As requested by @gardners 
Output adapted to tests.c restrictions: test # == suite number, subtest # in msg string.
=> Renamed qop_test to test_468

Makefile, src/tests/regression-tests.lst, src/tests/test_604.c, src/tests/test_604_asm.s
This PR adds a new test for issue #604
The test installs a raster irq handler, acknowledging the irq directly in the irq handler. It tests whether the raster irq handler gets called once or multiple times per frame. The fix for #604 ensures the raster irq will only be triggered once per frame.
=> feat: test #604 (raster irq not executing twice)

src/tools/fpgajtag/usbserial.c
removed unneeded code causing issues
=> fixing macOS autodiscover for older macos builds

Makefile
The `8/1 """\n"` pattern in the `hexdump` command causes the macOS version of hexdump to segfault. This pattern makes the ascii_font.c file more human readable by adding linefeeds, but is otherwise not needed to generate valid C. Removing it allows this rule to build on macOS.
Tested on macOS 12.6 and Ubuntu:
```
make src/tools/ascii_font.c
make bin/md2h65
./bin/md2h65
```
=> Remove cosmetic hexdump pattern that crashes macOS (BSD) hexdump

src/tools/mega65_ftp.c
That means you can give either the whole SD card (`/dev/sdN` or `/dev/diskN`) or the FAT32 partition directly (`/dev/sdNX` or `/dev/diskNsX`):
If no FAT32 partition is found in the MBR, it checks for the FAT32 file system signature and if that is present, uses the whole device file as the FAT32 partition.
Since the partition can now start at 0, I've changed the value for "no partition found" to 0xffffffff.
=> Support being given the FAT32 partition as SD card device.

Makefile
Updated Makefile to link macOS version of mega65_ftp statically against libusb, so end users don't have to manually install libraries on  their system. Will also help making m65connect easier to install for end users.
=> Link mega65_ftp.osx statically against libusb

.gitignore, .travis.yml, Makefile, conan/profile_macos_10.14_intel, conan/profile_macos_11_arm, conanfile.txt
This PR adds support for universal binaries to the Makefile. 3rd party libraries are fetched via Conan. Homebrew fetched packages can't be used easily for multi-arch binaries.
=> M1 and universal builds for macOS

src/utilities/fastload_demo.asm
Fix for issue discussed here: https://discord.com/channels/719326990221574164/782757495180361778/1142778850137362543
=> Fix irq fastloader copying one byte too many from last sector of file.

Makefile, include/etherload_common.h, src/tools/etherload/etherload.c, src/tools/etherload/etherload_common.c, src/tools/etherload/ethlet_all_done_basic2.a65, src/tools/etherload/ethlet_all_done_basic65.a65, src/tools/etherload/ethlet_set_ip_address.a65, src/tools/mega65_ftp.c, src/utilities/remotesd_eth.c
This changes the -I parameter of etherload and mega65_ftp so that it won't represent the network broadcast ip address but instead the ip address to be assigned to the MEGA65 for this connection. This allows to use any ip address for the MEGA65, not just x.y.z.65 as was the case before.
=> etherload and mega65_ftp supporting any ip address #178

src/tools/mega65_ftp.c
While mega65_ftp already takes care to trim off `"-quotes` it does not trim off `'-quotes`.
This PR add trimming of also for `'-quotes`. This is very convenient for `mega65_ftp` command line use on Linux.Because there when you drag-and-drop a file from Nautilus to the Gnome Terminal file-paths get automatically `'-quoted`.
=> mega65_ftp: trim off single quotes from string parameters

src/utilities/remotesd_eth.c
This fixes the build with cc65 V2.17.
=> Give all functions in remotesd_eth.c proper ANSI prototypes
